---
- name: Wishrem experiment deployment
  hosts: harry
  tasks:
  - name: Git clone wishrem_wifi_flex
    git: repo=https://github.com/wishful-project/wishrem_controllers_dockers.git dest=/tmp/wishrem_controllers_dockers
    become: yes
    
  - name: Copy code
    synchronize:
      src: /tmp/wishrem_controllers_dockers
      dest: ~/
      recursive: yes

  - name: Start docker services
    docker_service:
      project_src: ~/wishrem_controllers_dockers
      build: yes
      state: present
      restarted: true

- name: Wishrem experiment deployment
  hosts: nucs
  tasks:
  - name: Install packages
    apt: name="{{ item }}" state=present
    with_items:
    - wget
    - git
    - python
    - python-virtualenv
    - python-dev
    - python3-dev
    - python3-pip
    - rfkill
    - tshark
    - hostapd
    - hostap-utils
    - dnsmasq
    become: yes

  - name: Install pip packages
    pip:
      name: "{{ item }}"
      executable: pip3
      extra_args: -U
      editable: no
    with_items:
    - "pyshark"
    - "git+https://github.com/wishful-project/stream_pipe"
    - "git+https://github.com/wishful-project/python-tc"
    - "git+https://github.com/phaethon/scapy.git#egg=scapy-python3"
    - "git+https://github.com/uniflex/uniflex"
    - "git+https://github.com/uniflex/sbi"
    - "git+https://github.com/uniflex/module_net_linux"
    - "git+https://github.com/uniflex/module_wifi"
    - "git+https://github.com/wishful-project/pyre"
    - "git+https://github.com/uniflex/app_discovery_pyre"
    - "git+https://github.com/wishful-project/wishrem_rem_events"
    - "git+https://github.com/wishful-project/wishrem_wifi_flex"
    become: yes

  - name: Git clone wishrem_wifi_flex
    git: repo=https://github.com/wishful-project/wishrem_wifi_flex.git dest=/tmp/wishrem_wifi_flex
    become: yes
    
  - name: Copy node_app code
    synchronize:
      src: /tmp/wishrem_wifi_flex/node_app
      dest: ~/
      recursive: yes
