---
- name: Wishrem experiment deployment
  hosts: harry
  tasks:

  - name: Stop docker services
    docker_service:
      project_src: ~/wishrem/controllers_dockers
      build: yes
      state: absent
